### ISSUE TITLE
No counter_status_200 be found

### ISSUE THREAD

**Issue by wenfei3** [prometheus/client_java#415]
hello body,
I created a new spring-boot-web program and run it on my mac for testing,then I called the http api several times and I could read the metrics by http://localhost:6634/metrics:

```
# HELP counter_status_200_star_star_favicon_ico counter_status_200_star_star_favicon_ico
# TYPE counter_status_200_star_star_favicon_ico gauge
counter_status_200_star_star_favicon_ico 3.0
# HELP counter_status_200_metrics counter_status_200_metrics
# TYPE counter_status_200_metrics gauge
counter_status_200_metrics 2.0
# HELP counter_status_200_api_hello counter_status_200_api_hello
# TYPE counter_status_200_api_hello gauge
counter_status_200_api_hello 3.0
```
but I could not read the same metrics on other spring-boot-web programs which were running on the linux OS. Other metrics information can be displayed correctly.

the config for my program is
```
server:
  port: 6634
endpoints:
  enabled: false
  prometheus:
    enabled: true
    id: metrics
  health:
    enabled: true
    path: /health
management:
  security:
    enabled: false
  health:
    defaults:
      enabled: false
```

the client_java in my pom is
```
<dependency>
      <groupId>io.prometheus</groupId>
      <artifactId>simpleclient_spring_boot</artifactId>
      <version>0.5.0</version>
</dependency>
```

btw,is there any great grafana dashbord for client_java?
thank you very much!
